(() => {
'use strict';
const $ = (s, root=document) => root.querySelector(s);
const icons = {
 home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',
 sprout:'<path d="M12 21v-9M12 15C4 16 3 9 3 6c7 0 9 4 9 9ZM12 12c0-7 4-9 9-9 0 6-3 9-9 9Z"/>',
 compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5Z"/>',
 robot:'<rect x="4" y="7" width="16" height="13" rx="5"/><path d="M12 7V3M1 12v4m22-4v4M8 12v2m8-2v2m-7 3h6"/>',
 chart:'<path d="M4 3v18h17M8 16v-4m5 4V8m5 8V5"/>',
 heart:'<path d="M20 5c-3-3-6-1-8 1-2-2-5-4-8-1-5 5 3 12 8 15 5-3 13-10 8-15Z"/>',
 settings:'<path d="m9 3-1 3-3 1-2 4 2 2v4l4 3 3-1 3 1 4-3v-4l2-2-2-4-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/>',
 bell:'<path d="M5 17h14l-2-4V9a5 5 0 0 0-10 0v4ZM10 21h4"/>',
 chevron:'<path d="m9 5 7 7-7 7"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/>',
 focus:'<circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><circle cx="12" cy="12" r=".6"/>',
 bulb:'<path d="M9 18h6m-5 3h4M8 15c-6-6-1-13 4-13s10 7 4 13l-1 1H9Z"/>',
 wave:'<path d="M2 7c4-5 6 5 10 0s6 5 10 0M2 12c4-5 6 5 10 0s6 5 10 0M2 17c4-5 6 5 10 0s6 5 10 0"/>',
 clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
 leaf:'<path d="M20 3C7 1 1 9 5 17s17 3 15-14ZM5 20l9-10"/>',
 refresh:'<path d="M20 8a8 8 0 0 0-14-2L3 9m0-5v5h5M4 16a8 8 0 0 0 14 2l3-3m0 5v-5h-5"/>',
 gift:'<path d="M3 8h18v5H3Zm2 5v8h14v-8M12 8v13M12 8C1 8 4 0 9 3l3 5Zm0 0c11 0 8-8 3-5Z"/>',
 book:'<path d="M12 6C9 3 5 3 2 4v15c4-1 7-1 10 1 3-2 6-2 10-1V4c-3-1-7-1-10 2Zm0 0v14"/>',
 close:'<path d="m6 6 12 12M6 18 18 6"/>',
 volume:'<path d="m11 4-6 5H2v6h3l6 5Zm4 4c3 2 3 6 0 8m3-11c5 4 5 10 0 14"/>',
 pause:'<path d="M8 5v14M16 5v14"/>',
 check:'<path d="m5 12 4 4L19 6"/>',
 link:'<path d="m10 7 3-3c6-3 9 4 6 7l-3 3m-2 3-3 3c-6 3-9-4-6-7l3-3m0 6 8-8"/>',
 calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 10h18m-13 5h2m4 0h2"/>',
 download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',
 shield:'<path d="m12 2 9 4v7c0 5-9 9-9 9S3 18 3 13V6Zm-4 9 3 3 5-6"/>',
 mountain:'<path d="m2 20 8-15 5 9 3-6 5 12ZM7 11l3 2 3-2"/>',
 spark:'<path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Zm7 0v4m-2-2h4"/>',
 palette:'<path d="M12 3c-12 0-12 18 0 18 4 0 1-5 4-5h2c7-4 2-13-6-13Z"/><circle cx="7" cy="10" r="1"/><circle cx="11" cy="7" r="1"/><circle cx="16" cy="8" r="1"/>',
 hand:'<path d="M7 12V6c0-3 3-3 3 0v5-7c0-3 3-3 3 0v7-6c0-3 3-3 3 0v7-3c0-3 3-3 3 0v7c0 8-9 9-12 4L3 14c-2-3 1-5 4-2Z"/>'
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.spark}</svg>`;
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=[['explore','compass','天赋探索'],['home','home','今日陪伴'],['companion','robot','我的 DingDong'],['journey','sprout','成长旅程'],['reports','chart','成长观察'],['services','heart','家长支持']];
const moods=[['energy','sun','能量满满','来点小挑战'],['focus','focus','正在专注','慢慢做好一件事'],['inspire','bulb','需要启发','换个角度看看'],['calm','wave','平静如水','和自己待一会儿']];
const styles=[['cognitive','bulb','认知型引导','多问一个为什么','先猜一猜，再一起找答案。'],['imitative','hand','模仿型引导','看一看，再试试看','我先给一个例子，你可以做得不一样。'],['reverse','refresh','逆思型引导','给熟悉的事换个方向','如果反过来做，会有什么新发现？'],['open','spark','开放型引导','让想象自由发生','没有唯一答案，试试你的想法。']];
const tasks=[
{"id": "team-help", "mood": "calm", "name": "把一件小事，变成一次合作", "desc": "听听家人的需要，商量一件可以一起完成的小事。", "time": 3, "theme": "倾听与协作", "materials": "一位愿意参加的家人", "goal": "倾听需要并协商分工", "done": "说出对方的一个需要，并完成自己的小分工。", "alternative": "可以先画一张想帮助家人的小卡片。", "steps": ["问家人：今天有什么小事想请人帮忙？", "一起选择一件安全的小事，商量各自做哪一部分。", "做完后互相说一句感谢，聊聊哪里配合得好。"], "prompts": ["先听完，不急着给答案。对方最在意什么？", "你愿意做哪一步？也听听家人的想法。", "刚才哪个时刻，你觉得“我们一起做到了”？"]},{"id": "family-show", "mood": "energy", "name": "我是家庭小展览的发起人", "desc": "把喜欢的作品组织成一次小展览，邀请家人来看看。", "time": 3, "theme": "发起与组织", "materials": "两三件安全的小作品或绘画", "goal": "提出目标、邀请参与并安排步骤", "done": "确定一个展览主题，邀请一位观众并完成介绍。", "alternative": "可以用想象中的作品口头办展览。", "steps": ["挑选两三件作品，给小展览起一个主题。", "邀请一位家人参观，说说这场展览有什么特别。", "安排展示顺序，介绍作品，并听听观众的意见。"], "prompts": ["你想让大家从展览里发现什么？", "怎样介绍，能让家人愿意来看看？", "如果再办一次，你想做什么调整？"]},
 {id:'paper-bridge',mood:'energy',name:'一张纸，能搭一座桥吗？',desc:'和 DingDong 一起，把一个小猜想变成小发现。',time:3,theme:'科学小实验',materials:'一张纸、两本书、一块小橡皮',goal:'观察纸张形状与承重的关系',done:'尝试两种纸桥，说出一个观察到的不同。',alternative:'没有材料？用手势描述你想象中的桥。',steps:['把两本书放近一点，将纸平铺在中间。','把纸折成手风琴的样子，再放到两本书之间。','分别轻放小橡皮，比较哪一种纸桥更稳。'],prompts:['先别着急动手，你猜平平的纸能撑住小橡皮吗？','现在给纸变个形状吧。你觉得折痕会带来什么变化？','刚才发生了什么？用一句话告诉陪伴你的家人吧。']},
 {id:'shape-hunt',mood:'energy',name:'出发！寻找房间里的形状',desc:'用新的眼光，发现熟悉房间里的小秘密。',time:2,theme:'观察小挑战',materials:'身边安全、容易看到的物品',goal:'观察与分类',done:'指出三件不同形状的物品。',alternative:'坐着观察桌面上的物品也可以。',steps:['找一件圆圆的东西。','再找一件有直角的东西。','用自己的方式把它们分成两组。'],prompts:['不用跑远，就在你的周围找找看。','你是怎么认出这个形状的？','还可以按颜色或用途来分组吗？']},
 {id:'sound-map',mood:'focus',name:'闭上眼睛，画一张声音地图',desc:'把注意力交给耳朵，听见身边不一样的世界。',time:2,theme:'专注观察',materials:'一个安静、安全的位置',goal:'有意识地观察声音',done:'辨认两种声音，描述一个不同。',alternative:'不闭眼，也可以专注听声音。',steps:['舒服地坐好，安静听一小会儿。','找到一种近处的声音和一种远处的声音。','用自己的话描述，它们有什么不同。'],prompts:['不需要听到特别的声音，小小的也算。','你能分辨声音来自哪个方向吗？','我想听听你最先注意到的那个声音。']},
 {id:'sort-desk',mood:'focus',name:'给桌面的小伙伴排排队',desc:'按照自己的规则，让小物件各就各位。',time:3,theme:'分类与秩序',materials:'三至五件安全的小物品',goal:'发现与解释分类规则',done:'完成一次分类并说出规则。',alternative:'可以只用三支笔完成。',steps:['选几件桌面上安全的小物品。','想一个规则，把它们分组或排队。','告诉家人，你为什么这样安排。'],prompts:['看看它们，有什么共同点？','大小、颜色、用途，你想选哪个？','你的规则很有意思，还能换一种吗？']},
 {id:'cloud-story',mood:'inspire',name:'如果云朵有一份工作',desc:'和伙伴接一个故事，给想象一个出发的地方。',time:3,theme:'想象与表达',materials:'只需要你的想象',goal:'表达一个自己的想法',done:'说出云朵的工作和一个原因。',alternative:'也可以画一朵云，再指给家人看。',steps:['想象一朵特别的云，它长什么样？','给它安排一份工作。','说说它工作的第一天会发生什么。'],prompts:['圆圆的？长长的？还是一种从没见过的样子？','它可以给花浇水，也可以做你想到的任何事。','如果它遇到一个小麻烦，你会怎么帮它？']},
 {id:'new-use',mood:'inspire',name:'一把勺子的第二种人生',desc:'给日常物品想一个意想不到的新用途。',time:2,theme:'创意小剧场',materials:'想象中的一把勺子',goal:'从不同角度思考',done:'想出一个新用途并解释。',alternative:'可以换成纸杯或盒子。',steps:['想一想，勺子平时用来做什么。','如果不能用来吃东西，它还能做什么？','用动作演示你最喜欢的新用途。'],prompts:['先从你最熟悉的用途开始。','没有标准答案，奇怪的想法也很欢迎。','这个主意真特别！你想给它起个名字吗？']},
 {id:'small-thanks',mood:'calm',name:'收藏今天的一件小美好',desc:'慢慢想一想，今天有什么值得被记住。',time:2,theme:'生活小观察',materials:'一个舒服的位置',goal:'觉察日常经历并表达',done:'分享一件小事，或安静地回想片刻。',alternative:'不想分享也没关系，留在心里就好。',steps:['让身体坐得舒服一点。','想起今天一个让你舒服或开心的瞬间。','给这个瞬间起一个小小的名字。'],prompts:['我们可以慢一点，没有需要赶上的进度。','可能是一顿饭、一束光，或者一个拥抱。','谢谢你带我认识你的一天。安静陪着也很好。']},
 {id:'leaf-look',mood:'calm',name:'和一片叶子安静待一会儿',desc:'看见细微之处，发现一个从前没注意的细节。',time:2,theme:'自然观察',materials:'一片叶子，或窗外的一棵树',goal:'观察和描述细节',done:'发现一个形状、颜色或纹理的细节。',alternative:'看一件身边的物品也可以。',steps:['选一片叶子或一个想观察的物品。','看一看边缘、颜色和纹理。','指出一个你刚刚才注意到的细节。'],prompts:['先静静看，不急着说答案。','这条纹路让你想到了什么？','小小的发现，也值得被记住。']}
];
const KEY='dingdong-demo-v2';
const initial=()=>({version:2,name:'小小探索家',age:'',mood:'energy',style:'cognitive',taskId:'paper-bridge',records:[],active:null,consents:{data:false,personalization:false,reminders:false},assessment:{index:0,answers:[],completed:false},parentConfirmed:false});
let state=initial(),storageAvailable=true;
try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.version===2){state={...state,...s,consents:{...state.consents,...s.consents}};if(!Array.isArray(s.records)||!moods.some(m=>m[0]===s.mood)||!styles.some(m=>m[0]===s.style)||!tasks.some(t=>t.id===s.taskId)||!Array.isArray(s.assessment?.answers))state=initial();}}catch{storageAvailable=false;}
let currentRoute='',journeyFilter='all',reportPeriod='15d',feedback='',toastTimer,modalReturnFocus=null,speechToken=0;
const dialog=$('#dialog');
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageAvailable=true;}catch{storageAvailable=false;toast('浏览器无法保存，本次记录仅在当前页面保留。');}}
function uid(){return window.crypto?.randomUUID?.() || `demo-${Date.now()}-${Math.random().toString(16).slice(2)}`;}
function enteredFromNfc(){try{return Boolean(sessionStorage.getItem('dingdong-nfc'));}catch{return false;}}
function date(ts,detail=false){return new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',...(detail?{hour:'2-digit',minute:'2-digit'}:{weekday:'long'}),timeZone:'Asia/Shanghai'}).format(new Date(ts));}
function completedRecords(){return state.records.filter(r=>r.status==='completed');}
function selectedTask(){return tasks.find(t=>t.id===state.taskId)||tasks[0];}
function selectedStyle(){return styles.find(s=>s[0]===state.style)||styles[0];}
function fillIcons(){document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);});}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),4000);}
function pageHead(title,sub,eyebrow='GROW TOGETHER'){return `<div class="page-head"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${sub}</p></div><div class="date-chip">${icon('calendar')}${date(Date.now())}</div></div>`;}
function robot(cls=''){return `<img class="${cls}" src="assets/dingdong/robot-front.webp" alt="DingDong 提供的紫色机器人形象">`;}
function bridgeArt(){return `<svg viewBox="0 0 120 110" fill="none" aria-hidden="true"><ellipse cx="61" cy="90" rx="44" ry="8" fill="#e5dbc3"/><path d="M15 65h29v23H15Z" fill="#a3b9a3"/><path d="M15 65 22 58h27l-5 7Z" fill="#c4d2b9"/><path d="M76 65h29v23H76Z" fill="#d7b792"/><path d="M76 65 82 58h26l-3 7Z" fill="#e7d3b3"/><path d="m24 58 10-8 9 7 9-8 9 7 9-8 9 7 9-8 10 9v7l-10-7-9 8-9-7-9 8-9-7-9 8-9-7-10 8Z" fill="#fffdf1" stroke="#d4c8a7" stroke-linejoin="round"/><path d="m56 37 12-4 12 6-13 4Z" fill="#d9a477"/><path d="m56 37 11 6v10l-11-7Z" fill="#c28d62"/><path d="m67 43 13-4v11l-13 3Z" fill="#e5ba8c"/><path d="m94 21 2 5 5 2-5 2-2 5-2-5-5-2 5-2Z" fill="#d1b778"/><path d="M32 26v8m-4-4h8" stroke="#b4c8a3" stroke-width="2" stroke-linecap="round"/></svg>`;}
function home(){const t=selectedTask(),m=moods.find(m=>m[0]===state.mood),count=completedRecords().length;return `${pageHead(`嗨，${esc(state.name)} <span style="color:#d2ae65;font-weight:400">☀</span>`,'新的一天，和 DingDong 一起发现一点不一样。','A LITTLE WONDER, EVERY DAY')}${enteredFromNfc()?'<div class="nfc-note">已从机器人 NFC 入口进入。完成家长身份与设备权属验证后，才能关联真实设备。</div>':''}<div class="dashboard"><div class="main-column">
 <section class="hero" aria-label="DingDong 陪伴邀请"><div class="hero-copy"><span class="hero-tag"><i></i> 你的成长伙伴，已在这里等你</span><h2>今天，我们一起<br>发现<em>小小的可能。</em></h2><p>不急着成为谁。每一次好奇、每一个尝试，<br>都让我们更了解彼此。</p><button class="button" data-action="start-task">${icon('spark')}${state.active?'继续上次的小探索':'和 DingDong 开始探索'}${icon('arrow')}</button></div><div class="hero-art"><span class="float-star">✧</span><span class="float-star two">✦</span><span class="speech-sticker">今天想一起做点什么？</span>${robot('hero-robot')}<span class="hero-caption">YOUR LITTLE GROWTH COMPANION</span></div></section>
 <section class="mood-section"><div class="section-heading"><div><span class="step-badge">01</span><h2>现在的你，感觉怎么样？</h2></div><span class="small-print">每种状态，都很好</span></div><div class="mood-grid">${moods.map(([id,ic,name,sub])=>`<button class="mood-card ${state.mood===id?'selected':''}" data-action="mood" data-value="${id}" aria-pressed="${state.mood===id}"><span class="mood-symbol">${icon(ic)}</span><b>${name}</b><small>${sub}</small></button>`).join('')}</div></section>
 <section class="task-card"><div class="task-top"><div style="display:flex;align-items:center;gap:10px"><span class="step-badge">02</span><h2>给今天的一个小行动</h2></div><button class="text-button" data-action="rotate-task">${icon('refresh')} 换一个试试</button></div><div class="task-body"><div class="task-illustration">${bridgeArt()}</div><div class="task-copy"><span class="pill orange">${t.theme}</span><h3>${t.name}</h3><p>${t.desc}</p><div class="meta-row"><span>${icon('clock')}约 ${t.time} 分钟</span><span>${icon('leaf')}${m[2]}</span><span>${icon('robot')}伙伴引导演示</span></div></div></div><div class="task-footer"><span>小提示：准备好 ${t.materials.includes('、')?'身边的小材料':'一点属于自己的时间'}就可以开始。</span><div><button class="button ghost" data-action="task-detail">查看任务</button><button class="button secondary" data-action="start-task">${state.active?'继续小探索':'一起试试看'}${icon('arrow')}</button></div></div></section>
 <div class="explore-strip"><button class="explore-small" data-action="assessment"><span>${icon('compass')}</span><div><h3>认识独一无二的你</h3><p>从一份探索偏好体验开始</p></div>${icon('chevron')}</button><button class="explore-small" data-action="blindbox"><span>${icon('gift')}</span><div><h3>打开今日灵感盲盒</h3><p>给平凡的一天一个小惊喜</p></div>${icon('chevron')}</button></div>
 </div><aside class="side-column" aria-label="伙伴与成长摘要"><section class="card partner-card"><div class="section-heading"><h2>我的 DingDong</h2><span class="pill"><i class="status-dot"></i>设备未关联</span></div><div class="partner-profile"><div class="partner-avatar">${robot()}</div><div><h3>DingDong · 叮咚</h3><p>${selectedStyle()[3]} · 网页陪伴</p></div></div><div class="partner-quote">${selectedStyle()[4]}</div><div class="partner-actions"><button class="text-button" data-action="device">${icon('link')}关联机器人</button><a class="text-button" href="#companion">了解我的伙伴 ${icon('chevron')}</a></div></section>
 <section class="card journey-mini"><div class="section-heading"><h2>我们正在一起成长</h2><a class="text-button" href="#journey">${icon('arrow')}</a></div><div class="mini-timeline"><div class="timeline-point ${!state.assessment.completed?'current':''}"><b>初次相遇</b><small>${state.assessment.completed?'已完成探索体验':'从认识彼此开始'}</small></div><div class="timeline-point ${state.assessment.completed?'current':''}"><b>每一天的小探索</b><small>让好奇心，变成小小的行动</small></div><div class="timeline-point"><b>发现成长的足迹</b><small>回看记录，再认识彼此一次</small></div></div><div class="mini-progress"><span>网页已完成</span><div class="progress-track" aria-hidden="true"><i style="width:${Math.min(count*10,100)}%"></i></div><b>${count} 个小行动</b></div></section>
 <section class="card parent-card"><div class="eyebrow">A NOTE FOR PARENTS</div><h3>陪伴，不是催促。<br>看见，比评价更重要。</h3><p>从孩子的小行动里，读懂他正在发生的变化。</p><a class="text-button" href="#reports">打开家长观察室 ${icon('arrow')}</a><span class="parent-flower" aria-hidden="true">✳</span></section></aside></div>`;}
function journey(){const records=state.records.filter(r=>journeyFilter==='all'||r.status===journeyFilter).slice().reverse();const dates=new Set(completedRecords().map(r=>new Date(r.finishedAt).toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'})));return `${pageHead('每一小步，都有迹可循。','把尝试留在这里。今天休息，也不会失去已经走过的路。','OUR GROWTH JOURNEY')}<div class="stat-blocks"><div class="stat-card"><span>完成的小行动</span><b>${completedRecords().length}<small> 次</small></b><small>当前浏览器 · 网页自报</small></div><div class="stat-card"><span>留下足迹的日子</span><b>${dates.size}<small> 天</small></b><small>按实际完成日期去重</small></div><div class="stat-card"><span>机器人行为记录</span><b style="font-size:22px">尚未同步</b><small>关联设备并授权后可查看</small></div></div><div class="intro-banner"><div><h2>成长没有统一的速度。</h2><p>一次认真观察、一个新点子，都值得记住。</p></div><button class="button" data-action="start-task">${state.active?'继续小探索':'开始一个小行动'}${icon('arrow')}</button></div><div class="section-heading"><h2>我们的探索足迹</h2><button class="text-button" data-action="export">${icon('download')}导出网页记录</button></div><div class="tabs" role="group" aria-label="记录筛选">${[['all','全部足迹'],['completed','已完成'],['skipped','暂时跳过']].map(([id,n])=>`<button class="tab ${journeyFilter===id?'active':''}" aria-pressed="${journeyFilter===id}" data-action="filter" data-value="${id}">${n}</button>`).join('')}</div><div class="card">${records.length?records.map(r=>`<article class="record"><span class="record-dot">${icon(r.status==='completed'?'check':'leaf')}</span><div><h3>${esc(r.title)}</h3><p>${r.status==='completed'?'完成了一次探索':'给自己留一点空间，暂时跳过'}${r.feedback?' · '+esc(r.feedback):''}</p><small>${date(r.finishedAt,true)} · ${r.mode==='guide'?'伙伴引导演示':'网页步骤'} · 用户自报${r.note?' · 留有小发现':''}</small>${r.note?`<p>“${esc(r.note)}”</p>`:''}</div><span class="pill ${r.status==='completed'?'green':''}">${r.status==='completed'?'已完成':'已跳过'}</span></article>`).join(''):`<div class="empty-state">${icon('sprout')}<h3>${journeyFilter==='all'?'第一枚成长足迹，等你来留下。':'这里还没有对应的记录。'}</h3><p>和 DingDong 完成一次网页探索，就会记录在这里。</p><button class="button secondary" data-action="start-task">开启小探索 ${icon('arrow')}</button></div>`}</div><p class="source-footnote">这里的记录来自当前浏览器中的演示操作，不代表机器人自动采集，也不会换算为孩子的专业测评分数。</p>`;}
function explore(){return window.PlayWorld.render();}
function companion(){return `${pageHead('嗨，我是 DingDong 叮咚。','你带着好奇来，我陪你一步一步试。','MEET YOUR LITTLE COMPANION')}<div class="companion-layout"><section class="companion-stage"><span class="pill">DingDong 伙伴形象 · 网页互动预演</span>${robot()}<div class="stage-speech">${selectedStyle()[4]}<small>点击朗读，可以听到浏览器语音示范</small></div><button class="text-button" style="margin-top:16px" data-action="speak-intro">${icon('volume')}听听伙伴怎么说</button></section><section class="card"><div class="section-heading"><h2>你喜欢怎样一起探索？</h2></div><p class="muted" style="font-size:12px;line-height:1.9">选择今天喜欢的引导方式。它会改变网页任务中的提问，不会改变正式测评结果。</p><div class="style-options">${styles.map(([id,ic,n,sub])=>`<button class="style-option ${state.style===id?'active':''}" data-action="style" data-value="${id}" aria-pressed="${state.style===id}">${icon(ic)}<div><b>${n}</b><p>${sub}</p></div><span class="choice-circle"></span></button>`).join('')}</div><button class="button" data-action="start-task">一起做个小实验 ${icon('arrow')}</button><div class="note">网页偏好已保存；机器人配置尚未同步。当前使用 DingDong 提供的素材；设备远程设置仍需技术接入。</div><div class="key-value"><span>设备关联</span><button class="text-button" data-action="device">未关联 · 查看连接方式 ${icon('chevron')}</button></div></section></div>`;}
function reports(){const rows=completedRecords().filter(r=>Date.now()-new Date(r.finishedAt).getTime()<Number(reportPeriod.slice(0,-1))*86400000);return `${pageHead('看见成长，也看见过程。','一边是孩子留下的行动，一边是伙伴的陪伴；让每一条观察都有来源。','PARENTS’ OBSERVATION ROOM')}<div class="tabs" role="group" aria-label="观察窗口">${['15d','30d'].map(id=>`<button class="tab ${reportPeriod===id?'active':''}" data-action="period" data-value="${id}" aria-pressed="${reportPeriod===id}">近 ${id.slice(0,-1)} 天</button>`).join('')}</div><div class="report-grid"><section class="card"><div class="section-heading"><h2>孩子的成长观察</h2><span class="pill orange">阶段观察 · 非正式报告</span></div><div class="report-section"><h3><span>01</span>初次认识 · Baseline</h3><p>${state.assessment.completed?'探索偏好体验已完成，仅作互动参考。正式测评基线等待 CA 审核题库。':'尚未完成正式测评。可以先做一次探索偏好体验，熟悉参与方式。'}</p><button class="text-button" style="margin:10px 0 0 29px" data-action="assessment">${state.assessment.completed?'查看体验':'开始体验'}${icon('arrow')}</button></div><div class="report-section"><h3><span>02</span>行为足迹 · Evidence</h3><p>本浏览器在近 ${reportPeriod.slice(0,-1)} 天记录了 ${rows.length} 次完成的小行动。来源：用户自报；未包含机器人行为统计。</p><a class="text-button" style="margin:10px 0 0 29px" href="#journey">查看具体记录 ${icon('arrow')}</a></div><div class="report-section"><h3><span>03</span>再次认识 · Re-assessment</h3><p>正式回测尚未开放。回测节奏等待共同确认；15 / 30 天仅表示行为观察窗口。</p></div><div class="report-section"><h3><span>04</span>变化与发现 · Growth</h3><p>尚无可比较的正式测评结果。当前以行动时间线展示，不生成能力分数或增长曲线。</p></div><div class="report-section"><h3><span>05</span>下一个小行动 · Next Step</h3><p>试着问：“刚才你发现了什么？”给孩子一点表达的时间，也允许他说“还没想好”。</p></div></section><div class="side-column"><section class="card"><div class="section-heading"><h2>DingDong 的成长</h2><span class="pill">设备未关联</span></div><p style="font-size:11px;color:#8b968b">伙伴成长数值来自 DingDong 聚合接口，和 CA 专业测评分开呈现。</p><div class="metric-list">${[['companion','陪伴值'],['wisdom','智慧值'],['growth','综合成长值'],['action','行动 / 实践'],['creativity','创造力']].map(([k,v])=>`<div class="metric-row"><span>${v}</span><span data-metric="${k}">尚未同步</span></div>`).join('')}</div><div class="note">没有设备数据时保留空状态。网页任务完成不会直接增加机器人余额。</div><button class="text-button" style="margin-top:15px" data-action="device">${icon('link')}了解如何关联机器人</button></section><section class="card"><h2 style="font-size:16px">报告与数据说明</h2><p style="font-size:11px;color:#8e998e;margin:14px 0;line-height:1.9">专业报告将在正式测评、授权数据和审核模板齐备后生成。你可以随时导出当前网页探索记录。</p><button class="button ghost" data-action="export">${icon('download')}导出网页记录</button></section></div></div>`;}
function settings(){return `${pageHead('照顾好每一次连接。','管理探索档案、设备关联和数据使用选择。','YOUR SPACE, YOUR CHOICES')}<div class="settings-grid"><section class="card"><h2>探索家档案</h2><div class="settings-row"><div><b>${esc(state.name)}</b><p>${state.age?esc(state.age)+' · ':''}当前浏览器的演示档案</p></div><button class="text-button" data-action="profile">编辑 ${icon('chevron')}</button></div><div class="settings-row"><div><b>正式家长账户</b><p>待接入身份认证；演示档案不跨设备同步</p></div><span class="pill">尚未开放</span></div><div class="settings-row"><div><b>我的机器人</b><p>未关联 · 没有真实设备数据</p></div><button class="text-button" data-action="device">连接指引 ${icon('chevron')}</button></div></section><section class="card"><h2>数据与陪伴偏好</h2>${[['data','机器人行为数据共享','接入后，用约定的聚合数据补充成长观察'],['personalization','个性化引导配置','接入后，向设备提供必要的陪伴配置'],['reminders','机器人阶段提醒','接入后，提醒家长回到成长档案']].map(([id,n,sub])=>`<div class="settings-row"><div><b>${n}</b><p>${sub}</p></div><button class="switch" role="switch" aria-checked="${state.consents[id]}" aria-label="${n}演示偏好" data-action="consent" data-value="${id}"></button></div>`).join('')}<div class="small-print" style="margin-top:13px">这里仅保存演示偏好，不是正式授权。所有可选项默认关闭；没有向任何设备或服务传输资料。</div></section><section class="card"><h2>网页演示记录</h2><div class="settings-row"><div><b>导出我的记录</b><p>下载当前浏览器中的探索记录和偏好</p></div><button class="text-button" data-action="export">${icon('download')}导出</button></div><div class="settings-row"><div><b>清空演示记录</b><p>清空本浏览器的档案、任务和体验答案</p></div><button class="text-button" data-action="reset-dialog" style="color:#ad766c">清空</button></div></section><section class="card"><h2>关于这个成长空间</h2><p style="font-size:12px;color:#8d998f;line-height:2;margin-top:18px">CA × DingDong 天赋成长伙伴<br>互动演示 V4.0 · 基于项目 PRD V3.0<br>正式题库、角色素材与设备能力等待审核和联调。</p><a class="text-button" href="https://happykua.com/CareerAcademy.html" target="_blank" rel="noopener noreferrer" style="margin-top:18px">了解 Career Academy ${icon('arrow')}</a></section></div>`;}
function services(){return `${pageHead('陪孩子，也陪伴家长。','多一份理解，少一点催促。找到适合这个阶段的支持。','GROWTH IS A SHARED JOURNEY')}<div class="intro-banner"><div><h2>不急着给孩子一个答案。</h2><p>先看见他的尝试，再一起商量下一步。</p></div>${icon('heart')}</div><div class="service-list"><article class="service-item"><span>${icon('book')}</span><div><h3>把“小发现”变成一段好对话</h3><p>三个简单的问题，让亲子复盘更轻松。</p></div><button class="button secondary" data-action="parent-tips">阅读陪伴小建议</button></article><article class="service-item"><span>${icon('compass')}</span><div><h3>认识 Career Academy</h3><p>查看原有 CA 介绍，了解项目的专业内容提供方。</p></div><a class="button ghost" href="https://happykua.com/CareerAcademy.html" target="_blank" rel="noopener noreferrer">访问 CA 介绍 ${icon('arrow')}</a></article><article class="service-item"><span>${icon('chart')}</span><div><h3>带着记录，看见孩子的过程</h3><p>回顾具体行动和观察，保留孩子自己的表达。</p></div><a class="button secondary" href="#reports">查看成长观察 ${icon('arrow')}</a></article></div><div class="note">专业咨询服务、接收方和提交字段确认后再开放预约。当前页面不会自动向导师发送联系方式或儿童报告。</div>`;}
function render(){const nextRoute=location.hash.slice(1)||'explore';if(currentRoute!==nextRoute)window.FingerprintLab?.cleanup();currentRoute=nextRoute;const views={home,journey,explore,companion,reports,settings,services,fingerprint:()=>window.FingerprintLab.render()};if(!views[currentRoute]){location.hash='explore';return;}document.body.dataset.page=currentRoute;const label=currentRoute==='fingerprint'?'指纹探索':currentRoute==='settings'?'账户与设备':nav.find(n=>n[0]===currentRoute)?.[2]||'今日陪伴';$('#page-label').textContent=label;$('#header-name').textContent=state.name;document.title=`${label} · DingDong 天赋成长伙伴`;$('#main-nav').innerHTML=nav.map(([id,ic,n])=>`<a class="nav-link ${id===currentRoute?'active':''}" href="#${id}" ${id===currentRoute?'aria-current="page"':''}>${icon(ic)}${n}</a>`).join('');$('#mobile-nav').innerHTML=nav.slice(0,5).map(([id,ic,n])=>`<a href="#${id}" class="${id===currentRoute?'active':''}" ${id===currentRoute?'aria-current="page"':''}>${icon(ic)}${n==='我的 DingDong'?'伙伴':n}</a>`).join('');$('#main').innerHTML=`${!storageAvailable?'<div class="storage-warning">浏览器存储不可用，当前体验可能无法在刷新后保留。</div>':''}<div class="page">${views[currentRoute]()}</div>`;fillIcons();
 const art=$('.task-illustration');if(art&&selectedTask().id!=='paper-bridge'){art.innerHTML=icon({energy:'compass',focus:'focus',inspire:'spark',calm:'leaf'}[state.mood]);art.classList.add('symbol-art');}
 const decorativeProgress=$('.mini-progress .progress-track');if(decorativeProgress)decorativeProgress.remove();
 const journeyLink=$('.journey-mini .section-heading a');if(journeyLink)journeyLink.setAttribute('aria-label','查看完整成长旅程');
 if(currentRoute==='fingerprint'){window.FingerprintLab.mount();document.querySelectorAll('nav a[href="#explore"]').forEach(a=>{a.classList.add('active');a.setAttribute('aria-current','location');});}
 if(currentRoute==='explore')window.PlayWorld.mount();
}
function showDialog(title,body,foot='',eyebrow='DINGDONG · 一起慢慢来'){const already=dialog.open;stopSpeech();if(!already)modalReturnFocus=document.activeElement;$('#dialog-content').innerHTML=`<div class="dialog-head"><div><div class="eyebrow">${eyebrow}</div><h2 id="dialog-title">${title}</h2></div><button class="icon-button" data-action="close" aria-label="关闭弹窗">${icon('close')}</button></div>${body}${foot?`<div class="dialog-foot">${foot}</div>`:''}`;if(!already)dialog.showModal();else $('.dialog-head .icon-button').focus();}
function closeDialog(){stopSpeech();dialog.close();if(modalReturnFocus?.isConnected)modalReturnFocus.focus();}
function taskDetail(){const t=selectedTask();showDialog(t.name,`<div class="dialog-body"><p>${t.desc}</p><div class="task-details"><div><h3>准备材料 · 约 ${t.time} 分钟</h3><p>${t.materials}</p></div><div><h3>这次探索的小目标</h3><p>${t.goal}</p></div></div><ol class="instructions">${t.steps.map((s,i)=>`<li><span>${i+1}</span>${s}</li>`).join('')}</ol><div class="task-details"><div><h3>怎样就算完成</h3><p>${t.done}</p></div><div><h3>换一种方式也可以</h3><p>${t.alternative}</p></div></div><div class="note">互动示例内容，正式发布前需经 CA 审核。当前仅为网页预演，不会发送到实体机器人。</div></div>`,`<button class="button ghost" data-action="web-task">按网页步骤开始</button><button class="button" data-action="start-task">${state.active?'继续上次探索':'体验伙伴引导'}${icon('arrow')}</button>`);}
function startTask(mode='guide'){if(state.active&&state.active.taskId!==state.taskId){const previous=tasks.find(t=>t.id===state.active.taskId);showDialog('还有一个小探索，没有结束。',`<div class="dialog-body"><p>「${esc(previous?.name||'上次探索')}」已保留进度，可以随时继续。</p><div class="note">如果开始新的「${selectedTask().name}」，上次探索会记为“暂时跳过”，不会扣除任何成长值。</div></div>`,`<button class="button ghost" data-action="resume-existing">继续上次探索</button><button class="button" data-action="replace-task" data-value="${mode}">开始新的探索 ${icon('arrow')}</button>`);return;}if(!state.active)state.active={id:uid(),taskId:state.taskId,mode,step:0,startedAt:new Date().toISOString(),style:state.style};save();render();guide();}
function guide(){const a=state.active;if(!a)return;const t=tasks.find(t=>t.id===a.taskId);if(a.step>=t.steps.length){completionForm();return;}const st=styles.find(s=>s[0]===a.style)||styles[0];let speech=t.prompts[a.step];if(a.style==='imitative')speech=['先看一个例子：'+t.steps[0]+' 你也可以按自己的节奏来。','沿用刚才的做法试一试。哪里需要我再说一次？','照着做完以后，你最想改变哪个地方？'][a.step];if(a.style==='reverse')speech=['如果把熟悉的做法反过来，会发生什么？先试第一步。','有没有另一种做法？你可以选择比较，也可以先看眼前的结果。','刚才哪个发现和你最初的猜测不一样？'][a.step];if(a.style==='open')speech=['你想怎么开始？可以照着这一步，也可以用替代方案。','没有唯一的做法，看看你的想法会带来什么。','给今天的探索起个名字吧。你愿意的话，也可以分享给家人。'][a.step];showDialog(t.name,`<div class="task-dialog-grid"><div class="guide-robot"><span class="pill">${a.mode==='guide'?'伙伴引导演示':'网页自主探索'} · 非真机</span>${robot()}<p>${st[3]}<br>随时可以休息，下次再继续。</p></div><div class="guide-content"><div class="step-dots">${t.steps.map((s,i)=>`<i class="${i<=a.step?'active':''}"></i>`).join('')}<span>步骤 ${a.step+1} / ${t.steps.length}</span></div><h3>${t.steps[a.step]}</h3><p>${a.step===0?'准备：'+t.materials:'按你舒服的节奏来，不用着急。'}</p><div class="guide-speech" id="guide-speech">${a.mode==='guide'?speech:t.alternative}</div><button class="text-button" data-action="speak-step">${icon('volume')}朗读这一步</button></div></div>`,`<button class="text-button" data-action="skip-dialog" style="margin-right:auto">今天先休息</button>${a.step>0?'<button class="button ghost" data-action="prev-step">上一步</button>':''}<button class="button" data-action="next-step">${a.step===t.steps.length-1?'完成了，留个小脚印':'试好了，下一步'}${icon('arrow')}</button>`);}
function completionForm(){feedback='';showDialog('为今天的尝试，留一个小脚印。',`<div class="dialog-body"><div class="completion"><span class="success-icon">${icon('sprout')}</span><h3>谢谢你，和我一起试了试。</h3><p>不用做得完美。你的认真尝试，本身就值得被看见。</p></div><div class="feedback-options" role="group" aria-label="探索感受">${['很有意思','还想再试试','有一点挑战'].map(s=>`<button class="feedback-choice" data-action="feedback" data-value="${s}" aria-pressed="false">${s}</button>`).join('')}</div><label class="field">想记住的小发现 <span class="small-print">选填 · 只保存在当前浏览器</span><textarea id="discovery-note" maxlength="160" placeholder="比如：纸折起来以后，桥更稳了。"></textarea></label><div class="small-print">保存为网页自报记录，不作为机器人回执，也不会直接增加机器人游戏数值。</div></div>`,`<button class="button ghost" data-action="close">稍后再记</button><button class="button" data-action="finish-task">保存这次小探索 ${icon('check')}</button>`);}
function finishTask(status='completed'){const a=state.active;if(!a)return;const t=tasks.find(t=>t.id===a.taskId);if(state.records.some(r=>r.id===a.id)){state.active=null;save();closeDialog();render();return;}state.records.push({id:a.id,taskId:t.id,taskVersion:'demo-1',title:t.name,mode:a.mode,style:a.style,status,startedAt:a.startedAt,finishedAt:new Date().toISOString(),feedback:status==='completed'?feedback:'',note:status==='completed'?($('#discovery-note')?.value.trim()||''):'',source:'web_self_report',environment:'demo'});state.active=null;save();closeDialog();render();toast(status==='completed'?'小脚印已保存在网页成长旅程中。':'今天先休息也很好，下次再一起探索。');}
function rotateTask(){const list=tasks.filter(t=>t.mood===state.mood);state.taskId=list[(list.findIndex(t=>t.id===state.taskId)+1)%list.length].id;save();render();}
function device(){showDialog('把真实的 DingDong 带到这里。',`<div class="dialog-body"><p>关联后，网页可以在授权范围内接收伙伴的阶段成长数据。</p><div class="connection-steps"><div><b>1</b>准备好机器人<p>在已有的“智能生活 App”中完成设备联网。</p></div><div><b>2</b>手机触碰 NFC<p>打开联名网页，并完成家长账户登录。</p></div><div><b>3</b>验证与授权<p>确认设备权属，选择允许共享的数据范围。</p></div></div><div class="key-value"><span>真实设备</span><b>未关联</b></div><div class="key-value"><span>云端接口</span><b>待技术团队接入</b></div><div class="key-value"><span>设备执行回执</span><b>暂无</b></div><div class="note">当前没有可用的设备权属验证或远程任务接口。你仍然可以在网页中体验伙伴的分步引导，所有操作会明确标记为演示。</div></div>`,`<button class="button ghost" data-action="close">知道了</button><button class="button" data-action="start-task">先体验网页引导 ${icon('arrow')}</button>`);}
function profile(){showDialog('认识今天的小小探索家。',`<form id="profile-form"><div class="dialog-body"><p>为当前浏览器的演示档案起一个昵称。无需真实姓名、学校或精确生日。</p><label class="field">探索昵称<input id="nickname" name="nickname" value="${esc(state.name)}" maxlength="12" required autocomplete="off" placeholder="最多 12 个字"></label><label class="field">体验年龄段（选填）<select id="age"><option value="">暂不填写</option>${['6–8 岁','9–12 岁','13 岁及以上'].map(a=>`<option ${state.age===a?'selected':''}>${a}</option>`).join('')}</select></label><div class="small-print">年龄选项仅用于演示档案，不代表正式测评适用年龄。此页不进行登录或实名验证。</div></div><div class="dialog-foot"><button class="button ghost" type="button" data-action="close">取消</button><button class="button" type="submit">保存演示档案 ${icon('check')}</button></div></form>`);}
const questions=[{q:'遇到一件从没见过的小玩意儿，你更想先……',options:['弄清楚它为什么会这样','看别人怎么玩一次','试试不按说明会怎样','想出一种自己的新玩法']},{q:'和朋友一起搭积木，你会更想……',options:['想好怎样搭得更稳','参考一个喜欢的作品','试试换一个方向搭','边搭边编一个故事']},{q:'听完一个新故事，你最想聊的是……',options:['事情为什么会发生','主人公是怎么做到的','如果换一个结尾会怎样','故事之外还有什么可能']},{q:'下一次和 DingDong 探索，你想让它……',options:['多问几个为什么','先示范再陪我试','提出不一样的挑战','给我更多自由选择']}];
function assessment(){if(state.assessment.completed){assessmentResult();return;}const a=state.assessment,i=Math.min(a.index,3);a.index=i;const q=questions[i];showDialog('用你喜欢的方式，开始探索。',`<div class="dialog-body"><span class="pill orange">探索偏好体验 · 非正式测评</span><div class="meta-row" style="justify-content:space-between;margin-top:20px"><span>第 ${i+1} / 4 个小情境</span><span>${storageAvailable?'答案已自动保存在本浏览器':'当前仅在页面内保留'}</span></div><div class="progress-track" style="margin-top:12px"><i style="width:${(i+1)*25}%"></i></div><h3 class="question-title">${q.q}</h3>${q.options.map((s,j)=>`<button class="assessment-option ${a.answers[i]===j?'selected':''}" data-action="answer" data-value="${j}" aria-pressed="${a.answers[i]===j}">${s}</button>`).join('')}<p class="small-print" style="margin-top:18px">这些是流程演示情境，不是 CA 正式题库，不做天赋评分。选一个此刻最接近你的答案就好。</p></div>`,`<button class="button ghost" data-action="assessment-prev" ${i===0?'disabled':''}>上一个</button><button class="button" data-action="assessment-next" ${a.answers[i]===undefined?'disabled':''}>${i===3?'完成探索体验':'下一个情境'}${icon('arrow')}</button>`);}
function assessmentResult(){const counts=[0,0,0,0];state.assessment.answers.forEach(a=>{if(a>=0&&a<4)counts[a]++;});showDialog('原来，你有这么多探索的可能。',`<div class="dialog-body"><div class="completion"><span class="success-icon">${icon('compass')}</span><h3>4 个小情境，一次新的认识。</h3><p>这里记录的是本次选择，不是固定类型或能力结论。</p></div><div class="metric-list">${['先理解原理','先观察示范','试试不同角度','自由想象探索'].map((n,i)=>`<div class="metric-row"><span>${n}</span><span>本次选择 ${counts[i]} 次</span></div>`).join('')}</div><div class="note">你可以自由选择任何一种伙伴引导方式。正式天赋画像将在 CA 审核题库和评分规则接入后生成，本体验不建立正式 Baseline。</div></div>`,`<button class="button ghost" data-action="assessment-restart">重新体验</button><button class="button" data-action="to-companion">选择伙伴引导 ${icon('arrow')}</button>`);}
function blindbox(){showDialog('给今天的好奇，拆一份礼物。',window.PlayWorld.giftBody(moods.find(m=>m[0]===state.mood)[2]),`<button class="button" data-action="open-box">打开我的灵感盲盒 ${icon('spark')}</button>`);}
function islands(){closeDialog();window.PlayWorld.goToIslands();}
function stopSpeech(){speechToken++;if('speechSynthesis' in window)window.speechSynthesis.cancel();}
function speak(text,button){if(!('speechSynthesis' in window)){toast('当前浏览器不支持朗读，可以直接阅读页面引导。');return;}if(window.speechSynthesis.speaking){stopSpeech();if(button?.isConnected)button.innerHTML=icon('volume')+'再次朗读';return;}stopSpeech();const token=speechToken;const u=new SpeechSynthesisUtterance(text);u.lang='zh-CN';u.rate=.85;let started=false;const end=()=>{if(token===speechToken&&button?.isConnected)button.innerHTML=icon('volume')+'再次朗读';};u.onstart=()=>{started=true;};u.onend=end;u.onerror=()=>{end();if(token===speechToken)toast('语音暂时不可用，可以继续阅读文字引导。');};if(button)button.innerHTML=icon('pause')+'停止朗读';window.speechSynthesis.speak(u);setTimeout(()=>{if(token===speechToken&&!started){stopSpeech();if(button?.isConnected)button.innerHTML=icon('volume')+'再次朗读';toast('语音服务未响应，可以继续阅读文字引导。');}},5000);}
function exportData(){const payload={product:'CA × DingDong',environment:'demo',exportedAt:new Date().toISOString(),source:'current_browser',notice:'网页自报记录，不含真实机器人数据或正式测评结果',profile:{nickname:state.name,age:state.age},preferences:{style:state.style,consents:state.consents},exploration:state.assessment,islandExploration:window.IslandExplorer.exportData(),records:state.records};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`dingdong-explorations-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);toast('网页探索记录已导出。');}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const v=b.dataset.value;switch(b.dataset.action){
case 'close':closeDialog();break;
case 'mood':state.mood=v;state.taskId=tasks.find(t=>t.mood===v).id;save();render();toast('已为「'+moods.find(m=>m[0]===v)[2]+'」换好一个小行动。');break;
case 'rotate-task':rotateTask();break;
case 'task-detail':taskDetail();break;
case 'start-task':startTask();break;
case 'web-task':startTask('web');break;
case 'resume-existing':if(state.active){state.taskId=state.active.taskId;state.mood=selectedTask().mood;save();render();guide();}break;
case 'replace-task':finishTask('skipped');startTask(v==='web'?'web':'guide');break;
case 'next-step':if(state.active){state.active.step=Math.min(3,state.active.step+1);save();guide();}break;
case 'prev-step':if(state.active){state.active.step=Math.max(0,state.active.step-1);save();guide();}break;
case 'finish-task':finishTask();break;
case 'skip-dialog':showDialog('今天先到这里，也很好。',`<div class="dialog-body"><p>休息或换一个方向都没关系。这次探索会记录为“暂时跳过”，不会扣除任何成长值。</p></div>`,`<button class="button ghost" data-action="resume-guide">继续刚才的探索</button><button class="button secondary" data-action="skip-task">今天先休息</button>`);break;
case 'resume-guide':guide();break;
case 'skip-task':finishTask('skipped');break;
case 'feedback':feedback=v;$('.feedback-options').querySelectorAll('button').forEach(el=>{el.classList.toggle('active',el===b);el.setAttribute('aria-pressed',String(el===b));});break;
case 'filter':journeyFilter=v;render();break;
case 'period':reportPeriod=v;render();break;
case 'device':device();break;
case 'profile':profile();break;
case 'style':state.style=v;save();render();toast('已更新网页引导偏好，下次新探索会采用这种方式。');break;
case 'speak-intro':speak(selectedStyle()[4],b);break;
case 'speak-step':speak($('.guide-content h3')?.textContent+'。'+$('#guide-speech')?.textContent,b);break;
case 'assessment':assessment();break;
case 'answer':state.assessment.answers[state.assessment.index]=Number(v);save();assessment();break;
case 'assessment-prev':state.assessment.index=Math.max(0,state.assessment.index-1);save();assessment();break;
case 'assessment-next':if(state.assessment.answers[state.assessment.index]===undefined)return;if(state.assessment.index===3){state.assessment.completed=true;state.assessment.completedAt=new Date().toISOString();save();render();assessmentResult();}else{state.assessment.index++;save();assessment();}break;
case 'assessment-restart':state.assessment={index:0,answers:[],completed:false};save();render();assessment();break;
case 'to-companion':closeDialog();location.hash='companion';break;
case 'blindbox':blindbox();break;
case 'open-box':window.PlayWorld.openGift(()=>{rotateTask();taskDetail();});break;
case 'islands':islands();break;
case 'island':state.taskId=v;state.mood=selectedTask().mood;save();render();taskDetail();break;
case 'export':exportData();break;
case 'consent':state.consents[v]=!state.consents[v];save();render();toast(state.consents[v]?'已保存演示偏好；尚未向设备发送任何数据。':'已关闭该演示偏好。');break;
case 'reset-dialog':showDialog('清空这个浏览器的演示记录？',`<div class="dialog-body"><p>将删除本地探索昵称、任务记录、进行中的任务和体验答案。建议先导出留存。此操作不涉及真实 CA 或 DingDong 账户。</p></div>`,`<button class="button ghost" data-action="close">保留记录</button><button class="button danger" data-action="reset">确认清空本地演示</button>`);break;
case 'reset':window.IslandExplorer.reset();state=initial();save();closeDialog();location.hash='explore';render();toast('当前浏览器的演示档案已重置。');break;
case 'notifications':showDialog('成长提醒，按自己的节奏。',`<div class="dialog-body"><div class="empty-state">${icon('bell')}<h3>${state.active?'还有一个小探索，等你继续。':'今天没有需要赶上的进度。'}</h3><p>正式回测时间和机器人提醒尚未配置。<br>这里不会因为休息一天，就错过什么。</p></div></div>`,`<button class="button secondary" data-action="${state.active?'start-task':'close'}">${state.active?'继续探索':'知道了'}</button>`);break;
case 'parent-tips':showDialog('把评价，换成好奇的提问。',`<div class="dialog-body"><p>完成小任务之后，留一点时间听孩子说。不必每个问题都回答。</p><ol class="instructions"><li><span>1</span>“刚才哪一小步，你最喜欢？”</li><li><span>2</span>“有没有什么和你想的不一样？”</li><li><span>3</span>“下次你还想试点什么？”</li></ol><div class="note">如果孩子不想说，也可以：“好呀，等你想分享的时候，我都在。”<br>以上为演示陪伴文案，正式内容需由 CA 审核。</div></div>`,`<button class="button secondary" data-action="close">留点时间，听听孩子</button>`);break;
}});
document.addEventListener('submit',e=>{if(e.target.id!=='profile-form')return;e.preventDefault();const input=$('#nickname');const value=input.value.trim();if(!value){input.setCustomValidity('请填写一个探索昵称');input.reportValidity();return;}state.name=value.slice(0,12);state.age=$('#age').value;save();closeDialog();render();toast('探索档案已保存在当前浏览器。');});
document.addEventListener('input',e=>{if(e.target.id==='nickname')e.target.setCustomValidity('');});
dialog.addEventListener('cancel',stopSpeech);
dialog.addEventListener('close',stopSpeech);
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
window.addEventListener('hashchange',()=>{if(dialog.open)closeDialog();render();window.scrollTo({top:0});});
window.addEventListener('beforeunload',()=>{stopSpeech();window.FingerprintLab?.cleanup();});
// NFC is an entry signal only. Never retain the actual token in demo storage or turn it into a binding.
try{const url=new URL(location.href);if(url.searchParams.has('nfc_token')||url.searchParams.has('source_token')){sessionStorage.setItem('dingdong-nfc','entry-seen');url.searchParams.delete('nfc_token');url.searchParams.delete('source_token');history.replaceState(null,'',url.pathname+url.search+url.hash);}}catch{}
window.PlayWorld.bind({dialog:showDialog,close:closeDialog,toast,task(id){state.taskId=id;state.mood=selectedTask().mood;save();render();taskDetail();}});
render();
})();
