/* Reference material supplied with capage: four discussion guides, not diagnostic rules. */
(() => {
 'use strict';
 const guides={
  whorl:{name:'斗纹',code:'W',title:'认知型',lead:'先理解，再出发',color:'#a97738',shape:'中心纹路呈环形或螺旋状，像一个小漩涡。',angle:['原资料以“自己发现、自己领悟”描述这一组，关注自主思考和对原因的好奇。','可以观察：孩子是否常问“为什么”，是否喜欢自己决定先做哪一步。','把目标和理由说清楚，再邀请孩子表达自己的想法。'],learning:['先讲清原理，再尝试记忆；用“你猜会怎样”开启探索。','提供两个可选方案，让孩子参与目标和方法的选择。','将大目标拆成小实验，鼓励用观察结果修正想法。'],communication:['多商量、少命令，先认真听完孩子的理由。','先肯定具体的尝试，再提出一个可执行的小建议。','讨论问题时留出思考时间，避免公开贴标签。'],prompt:'“你觉得为什么会这样？我们可以怎样验证？”',style:'认知型引导'},
  loop:{name:'正箕纹',code:'L',title:'模仿型',lead:'看见例子，再试试看',color:'#467f89',shape:'纹路从一侧进入，回转后从同侧离开；判断箕纹方向还需结合左右手和手指朝向。',angle:['原资料以“先找参考、通过示范学习”描述这一组，重视环境和具体例子。','可以观察：孩子是否希望先看一遍，是否在熟悉的步骤中更容易开始。','示范是起点，也给孩子留下改变做法、形成自己想法的空间。'],learning:['先完整示范一个小步骤，再邀请孩子亲手尝试。','选择清楚、积极的例子；让重复练习有变化和反馈。','用简短清单展示顺序，熟悉后逐步减少提示。'],communication:['给出具体、清楚的说明，必要时一条一条讲。','面对新环境，提前介绍会发生什么，允许慢慢适应。','询问“你想参考哪一种”，鼓励表达自己的选择。'],prompt:'“我们先看一个例子。轮到你时，你想保留什么、改变什么？”',style:'模仿型引导'},
  reverse:{name:'反箕纹',code:'R',title:'逆思型',lead:'换个方向，发现新办法',color:'#8f71b2',shape:'同属回转的箕形纹路；开口相对方向需结合手别判断，不能仅凭照片左右区分。',angle:['原资料以“从结果倒推、从不同角度想”描述这一组，关注逆向思考。','可以观察：孩子是否爱问“如果反过来呢”，是否愿意提出不同方案。','不同意见值得被倾听，表达方式也可以在日常合作中练习。'],learning:['从一个结果倒推过程，例如给故事想出另一种开头。','用开放的问题和适度挑战，引导比较不同解决办法。','允许安全范围内的试错，并一起回顾发生了什么。'],communication:['先接纳不同观点，再一起讨论理由和证据。','用“我听到你的想法是……”帮助彼此确认理解。','把意见说具体，练习尊重地表达分歧，不用激将或贴标签。'],prompt:'“如果换一个方向，会有什么不一样？我们试着找个证据。”',style:'逆思型引导'},
  arch:{name:'弧纹',code:'X',title:'开放型',lead:'多种体验，一点点积累',color:'#69834b',shape:'纹路由一侧升起，在中部形成弧形，再向另一侧落下，像一座小山丘。',angle:['原资料以“开放接收、多样体验”描述这一组，重视持续的学习机会。','可以观察：孩子对哪些新体验好奇，什么样的讲解和节奏更舒服。','每个孩子都需要支持；纹路不能决定孩子的可塑性或学习能力。'],learning:['提供多种可以选择的体验，观察孩子愿意重复哪一种。','一次给出一个明确的小目标，用稳定、适度的练习积累经验。','把讲解变成看得见的例子或情境，让孩子尝试后说出发现。'],communication:['说明清楚、前后一致，避免一次给太多指令。','肯定具体行为，让孩子知道自己做到了哪一步。','提供适合当下节奏的帮助，再逐渐增加自主选择。'],prompt:'“今天想先认识哪一种新玩法？我们从一个小步骤开始。”',style:'开放型引导'},
 };
 function render(id){const g=guides[id];if(!g)return '';return `<section class="fp-guide-report" id="fp-guide-report" aria-labelledby="fp-guide-title" style="--guide-color:${g.color}"><header class="fp-guide-header"><img src="assets/fingerprints/${id}.webp" alt="${g.name}原始示意图" width="112" height="112"><div><span class="fp-manual-label">你的手动选择 · ${g.name}</span><h2 id="fp-guide-title">${g.title} <b>${g.code}</b><small>${id==='arch'?'原资料亦标注 A / X':''}</small></h2><p>${g.lead}</p></div><span class="fp-guide-stamp">探索<br>参考卡</span></header><div class="fp-guide-source"><b>关于这张参考卡</b><p>“${g.name}—${g.title}”及下方内容整理自提供的原始资料。它不是本产品验证过的心理测评对应关系，也不是由照片识别出的能力或性格结论。可以把建议当作亲子沟通的尝试，按孩子的实际反应选择。</p></div><div class="fp-guide-shape"><b>先认识纹路</b><p>${g.shape}</p></div><div class="fp-guide-columns">${[['01','原资料的观察角度',g.angle],['02','可以试试的学习方式',g.learning],['03','可以试试的沟通方式',g.communication]].map(([n,title,items])=>`<article><span>${n}</span><h3>${title}</h3><ul>${items.map(t=>`<li>${t}</li>`).join('')}</ul></article>`).join('')}</div><div class="fp-guide-dialogue"><img src="assets/dingdong/robot-wave.webp" alt="DingDong" width="90" height="90"><div><span>让建议，变成一次真实的对话</span><p>${g.prompt}</p><small>在“我的 DingDong”中可自由选择${g.style}；不会根据指纹自动设置。</small></div><a class="button" href="#companion">看看伙伴的引导 →</a></div><p class="fp-guide-footnote">内容依据：capage 原始指纹说明与四组学习风格资料，经儿童场景整理。四类没有优劣之分，不用于职业推荐、能力评分或人格定型。</p></section>`;}
 window.FingerprintGuide={guides,render};
})();
