(() => {
 'use strict';
 let revealTimer=null;
 const arrow='<span aria-hidden="true">→</span>';
 function render(){return window.IslandExplorer.render()+`<section class="discovery-portals" aria-label="更多天赋探索入口"><div class="portal-section-heading"><h2>好奇心，还有这些打开方式</h2><span>和 DingDong 一起，慢慢认识自己</span></div><div class="portal-grid">
 <button class="discovery-portal radar-portal" data-action="assessment"><div class="portal-art"><img class="portal-supplied-art" src="assets/dingdong/island-S.webp" alt="DingDong 邀请你探索" loading="lazy"><span class="portal-sticker">4 个小情境</span></div><div class="portal-copy"><span class="portal-kicker">HOW WE EXPLORE</span><h3>我的探索方式</h3><p>喜欢先问原因，还是先看示范？找到今天舒服的玩法。</p><span class="portal-go">试试探索偏好体验 →</span></div></button>
 <a class="discovery-portal fingerprint-portal" href="#fingerprint"><div class="portal-art"><img class="portal-fingerprint" src="assets/fingerprints/whorl.webp" alt="原始斗纹示意图" loading="lazy"><span class="portal-sticker">原图对照 · 四类参考说明</span></div><div class="portal-copy"><span class="portal-kicker">TINY LINES, BIG WONDER</span><h3>指纹小宇宙</h3><p>对照指尖的纹路，阅读对应的学习与沟通参考卡。</p><span class="portal-go">打开指纹探索 →</span></div></a>
 <button class="discovery-portal gift-portal" data-action="blindbox"><div class="portal-art"><img class="portal-supplied-art" src="assets/dingdong/gift.webp" alt="DingDong 和惊喜礼盒" loading="lazy"><span class="portal-sticker">今天的小惊喜</span></div><div class="portal-copy"><span class="portal-kicker">A SURPRISE JUST FOR YOU</span><h3>灵感惊喜盲盒</h3><p>把一个意想不到的小行动，装进今天的生活。</p><span class="portal-go">拆开看看 →</span></div></button>
 </div></section><div class="explore-kind-note"><img src="assets/dingdong/robot-front.webp" alt=""><p>兴趣可以不止一种，答案也可以慢慢改变。<b>跟着好奇心走，就很好。</b></p></div>`;}
 function gift(large=true){return `<div class="toy-gift ${large?'large':''}"><span class="gift-glow"></span><span class="gift-box"><i></i><b></b></span><span class="gift-lid"><i></i><b></b><em></em></span><span class="gift-star star-a">✦</span><span class="gift-star star-b">✧</span><span class="gift-star star-c">✦</span></div>`;}
 function giftBody(mood){return `<div class="dialog-body mystery-room"><span class="mystery-tag">DINGDONG’S LITTLE SURPRISE</span><div class="gift-stage">${gift()}<div class="gift-confetti" aria-hidden="true">${Array.from({length:12},(_,i)=>`<i style="--i:${i};--r:${i*30}deg"></i>`).join('')}</div></div><h3>嘘……这里面藏着一个小惊喜。</h3><p>给「${mood}」的你，<br>装进一个现在就能开始的小行动。</p><small>免费灵感体验 · 可以按自己的节奏再试试</small></div>`;}
 function openGift(reveal){const room=document.querySelector('.mystery-room');if(!room||room.classList.contains('opening'))return;room.classList.add('opening');const button=document.querySelector('[data-action="open-box"]');if(button){button.disabled=true;button.textContent='正在打开小惊喜…';}clearTimeout(revealTimer);revealTimer=setTimeout(()=>{if(room.isConnected&&document.querySelector('#dialog')?.open){reveal();burst();}},window.matchMedia('(prefers-reduced-motion: reduce)').matches?80:1250);}
 function burst(){const layer=document.createElement('div');layer.className='celebration-particles';layer.setAttribute('aria-hidden','true');layer.innerHTML=Array.from({length:24},(_,i)=>`<i style="--i:${i};--x:${(i%8)*13-45}vw;--r:${i*39}deg"></i>`).join('');document.body.append(layer);setTimeout(()=>layer.remove(),1800);}
 window.PlayWorld={render,mount(){},bind(callbacks){window.IslandExplorer.bind(callbacks);},giftBody,openGift,burst,goToIslands(){window.IslandExplorer.goToIslands();}};
})();
