(() => {
 'use strict';
 let revealTimer=null;
 const arrow='<span aria-hidden="true">→</span>';
 function render(){return window.IslandExplorer.render()+talentSection()+`<section class="discovery-portals" aria-label="更多天赋探索入口"><div class="portal-section-heading"><h2>把发现，带进每一天</h2><span>观察与行动 · 两种轻松的开始</span></div><div class="portal-grid portal-grid-two">

 <a class="discovery-portal fingerprint-portal" href="#fingerprint"><div class="portal-art"><img class="portal-fingerprint" src="assets/fingerprints/whorl.webp" alt="斗纹示意图" loading="lazy"><span class="portal-sticker">03 · 纹路与陪伴</span></div><div class="portal-copy"><span class="portal-kicker">TINY LINES, BIG WONDER</span><h3>指纹小宇宙</h3><p>认识四种纹路，找到清楚的学习建议、沟通示例和亲子小行动。</p><span class="portal-go">打开指纹探索 →</span></div></a>
 <button class="discovery-portal gift-portal" data-action="blindbox"><div class="portal-art"><img class="portal-supplied-art" src="assets/dingdong/gift.webp" alt="DingDong 和惊喜礼盒" loading="lazy"><span class="portal-sticker">04 · 今日小行动</span></div><div class="portal-copy"><span class="portal-kicker">A SURPRISE JUST FOR YOU</span><h3>灵感惊喜盲盒</h3><p>把一个意想不到的小行动，装进今天的生活。</p><span class="portal-go">拆开看看 →</span></div></button>
 </div></section><div class="explore-kind-note"><img src="assets/dingdong/robot-front.webp" alt=""><p>兴趣可以不止一种，答案也可以慢慢改变。<b>跟着好奇心走，就很好。</b></p></div>`;}
 function talentSection(){return `<section class="talent-module" aria-label="八大天赋优势模块"><div class="module-heading" style="--module:#765492"><b>02</b><div><h2>八大天赋优势 · 我有哪些表现</h2><p>从真实生活中的 24 个细节，了解语言、音乐、逻辑等八个维度。</p></div><span>24 题 · 约 5–8 分钟</span></div>${window.TalentExplorer.summary()}<div class="talent-dimension-chips">${window.TalentData.dimensions.map(d=>`<span><i aria-hidden="true">${d.icon}</i>${d.name}</span>`).join('')}</div><p class="module-outcome"><b>完成后可以看到</b>八维雷达 · 每项表现解读 · 适合本周尝试的小活动</p></section>`;}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-module-scroll]');if(b)document.getElementById(b.dataset.moduleScroll)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});});
 function gift(large=true){return `<div class="toy-gift ${large?'large':''}"><span class="gift-glow"></span><span class="gift-box"><i></i><b></b></span><span class="gift-lid"><i></i><b></b><em></em></span><span class="gift-star star-a">✦</span><span class="gift-star star-b">✧</span><span class="gift-star star-c">✦</span></div>`;}
 function giftBody(mood){return `<div class="dialog-body mystery-room"><span class="mystery-tag">DINGDONG’S LITTLE SURPRISE</span><div class="gift-stage">${gift()}<div class="gift-confetti" aria-hidden="true">${Array.from({length:12},(_,i)=>`<i style="--i:${i};--r:${i*30}deg"></i>`).join('')}</div></div><h3>嘘……这里面藏着一个小惊喜。</h3><p>给「${mood}」的你，<br>装进一个现在就能开始的小行动。</p><small>免费灵感体验 · 可以按自己的节奏再试试</small></div>`;}
 function openGift(reveal){const room=document.querySelector('.mystery-room');if(!room||room.classList.contains('opening'))return;room.classList.add('opening');const button=document.querySelector('[data-action="open-box"]');if(button){button.disabled=true;button.textContent='正在打开小惊喜…';}clearTimeout(revealTimer);revealTimer=setTimeout(()=>{if(room.isConnected&&document.querySelector('#dialog')?.open){reveal();burst();}},window.matchMedia('(prefers-reduced-motion: reduce)').matches?80:1250);}
 function burst(){const layer=document.createElement('div');layer.className='celebration-particles';layer.setAttribute('aria-hidden','true');layer.innerHTML=Array.from({length:24},(_,i)=>`<i style="--i:${i};--x:${(i%8)*13-45}vw;--r:${i*39}deg"></i>`).join('');document.body.append(layer);setTimeout(()=>layer.remove(),1800);}
 window.PlayWorld={render,mount(){},bind(callbacks){window.IslandExplorer.bind(callbacks);},giftBody,openGift,burst,goToIslands(){window.IslandExplorer.goToIslands();}};
})();
