# Generated by Django 6.0.8 on 2026-09-11 05:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestFixture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dataset", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=32)),
                ("subject_key", models.CharField(max_length=128)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("payload", models.JSONField()),
                ("consumed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "test_fixture",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset", "kind", "subject_key", "sequence"),
                        name="fixture_natural_key",
                    )
                ],
            },
        ),
    ]
