# Generated by Django 6.0.8 on 2026-09-11 05:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityContentVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("version", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=120)),
                ("island", models.CharField(max_length=32)),
                ("mood", models.CharField(max_length=32)),
                ("duration_minutes", models.PositiveSmallIntegerField()),
                ("content", models.JSONField()),
                ("status", models.CharField(default="draft", max_length=16)),
                ("data_origin", models.CharField(max_length=16)),
                ("published_at", models.DateTimeField(null=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_content_version",
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("action", models.CharField(max_length=64)),
                ("target_kind", models.CharField(max_length=64)),
                ("target_id", models.UUIDField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_event",
            },
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("create_request_key", models.UUIDField()),
                ("create_payload", models.JSONField()),
                ("name", models.CharField(max_length=80)),
                ("gender", models.CharField(default="unknown", max_length=16)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="active", max_length=16)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "child",
            },
        ),
        migrations.CreateModel(
            name="ActivityRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("create_request_key", models.UUIDField()),
                ("mode", models.CharField(max_length=16)),
                ("style", models.CharField(max_length=32)),
                ("status", models.CharField(default="active", max_length=16)),
                ("step_index", models.PositiveIntegerField(default=0)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("feedback", models.CharField(max_length=32, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=160)),
                ("source", models.CharField(default="web_self_report", max_length=24)),
                (
                    "activity_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.activitycontentversion",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.child"),
                ),
            ],
            options={
                "db_table": "activity_record",
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="active", max_length=16)),
            ],
            options={
                "db_table": "family",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "frozen", "closed"])),
                        name="family_status_valid",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="child",
            name="family",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.family"),
        ),
        migrations.CreateModel(
            name="FamilyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(default="owner", max_length=16)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.family"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "family_membership",
            },
        ),
        migrations.CreateModel(
            name="LoginGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("current_refresh_jti", models.UUIDField(unique=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                ("revoke_reason", models.CharField(blank=True, max_length=32)),
                ("last_refreshed_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "login_grant",
            },
        ),
        migrations.CreateModel(
            name="SmsChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=16)),
                ("client_ip", models.GenericIPAddressField()),
                ("purpose", models.CharField(default="login", max_length=24)),
                ("code_digest", models.CharField(max_length=64, null=True)),
                ("status", models.CharField(default="sent", max_length=16)),
                ("failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "sms_challenge",
                "indexes": [
                    models.Index(
                        fields=["phone", "created_at"], name="sms_challen_phone_59b4ea_idx"
                    ),
                    models.Index(
                        fields=["client_ip", "created_at"], name="sms_challen_client__9709a1_idx"
                    ),
                    models.Index(fields=["expires_at"], name="sms_challen_expires_90df2b_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("failed_attempts__lte", 5)), name="sms_attempt_limit"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("status__in", ["sent", "consumed", "expired", "locked"])
                        ),
                        name="sms_status_valid",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="activitycontentversion",
            constraint=models.UniqueConstraint(
                fields=("code", "version"), name="activity_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycontentversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("code",),
                name="activity_one_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycontentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "published", "retired"])),
                name="activity_content_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycontentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_origin__in", ["synthetic", "live"])),
                name="activity_origin",
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycontentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gt", 0)), name="activity_duration_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="activityrecord",
            index=models.Index(
                fields=["child", "status", "finished_at"], name="activity_re_child_i_122658_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.UniqueConstraint(
                fields=("started_by", "create_request_key"), name="activity_create_idempotent"
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("child",),
                name="child_one_active_activity",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "completed", "skipped"])),
                name="activity_record_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("mode__in", ["guide", "web"])), name="activity_record_mode"
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", "web_self_report")), name="activity_source_web"
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("finished_at__isnull", True), ("status", "active")),
                    models.Q(
                        ("finished_at__isnull", False), ("status__in", ["completed", "skipped"])
                    ),
                    _connector="OR",
                ),
                name="activity_finished_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "skipped"), _negated=True),
                    models.Q(("feedback__isnull", True), ("note", "")),
                    _connector="OR",
                ),
                name="skipped_without_feedback",
            ),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("finished_at__isnull", True),
                    ("finished_at__gte", models.F("started_at")),
                    _connector="OR",
                ),
                name="activity_time_order",
            ),
        ),
        migrations.AddIndex(
            model_name="child",
            index=models.Index(
                fields=["family", "status", "created_at"], name="child_family__37cc6b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="child",
            constraint=models.UniqueConstraint(
                fields=("created_by", "create_request_key"), name="child_create_idempotent"
            ),
        ),
        migrations.AddConstraint(
            model_name="child",
            constraint=models.CheckConstraint(
                condition=models.Q(("gender__in", ["unknown", "male", "female"])),
                name="child_gender_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="child",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["active", "archived"])),
                name="child_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="familymembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("family",),
                name="family_one_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="familymembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_at__isnull", True)),
                fields=("user",),
                name="parent_one_family",
            ),
        ),
        migrations.AddConstraint(
            model_name="familymembership",
            constraint=models.CheckConstraint(
                condition=models.Q(("role", "owner")), name="membership_role_owner"
            ),
        ),
        migrations.AddIndex(
            model_name="logingrant",
            index=models.Index(
                fields=["user", "created_at"], name="login_grant_user_id_ff95fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="logingrant",
            index=models.Index(fields=["expires_at"], name="login_grant_expires_ddae88_idx"),
        ),
    ]
