# Generated by Django 6.0.8 on 2026-09-11 05:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(default="report", max_length=32)),
                ("business_key", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(default="pending", max_length=24)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=5)),
                ("next_attempt_at", models.DateTimeField(null=True)),
                ("execution_token", models.UUIDField(null=True)),
                ("lease_expires_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(max_length=64, null=True)),
            ],
            options={
                "db_table": "background_job",
            },
        ),
        migrations.CreateModel(
            name="AssessmentSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("create_request_key", models.UUIDField()),
                ("status", models.CharField(default="draft", max_length=24)),
                ("answers", models.JSONField(default=dict)),
                ("input_context", models.JSONField(default=dict)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                ("submitted_at", models.DateTimeField(null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "child",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.child"),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "assessment_session",
            },
        ),
        migrations.CreateModel(
            name="AlgorithmAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_no", models.PositiveIntegerField()),
                ("request_id", models.UUIDField(unique=True)),
                ("request_revision", models.PositiveBigIntegerField()),
                ("provider", models.CharField(default="database_fixture", max_length=64)),
                ("algorithm_version", models.CharField(max_length=128, null=True)),
                ("status", models.CharField(default="running", max_length=24)),
                ("started_at", models.DateTimeField()),
                ("deadline_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(max_length=64, null=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.assessmentsession"
                    ),
                ),
            ],
            options={
                "db_table": "algorithm_attempt",
            },
        ),
        migrations.CreateModel(
            name="ConsentGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("purpose", models.CharField(max_length=32)),
                ("create_request_key", models.UUIDField()),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "child",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.child"),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "consent_grant",
            },
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="consent_grant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.consentgrant"
            ),
        ),
        migrations.CreateModel(
            name="JobAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_no", models.PositiveIntegerField()),
                ("execution_token", models.UUIDField(unique=True)),
                ("status", models.CharField(max_length=16)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(max_length=64, null=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.backgroundjob"
                    ),
                ),
            ],
            options={
                "db_table": "job_attempt",
            },
        ),
        migrations.CreateModel(
            name="PolicyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("version", models.CharField(max_length=32)),
                ("status", models.CharField(default="draft", max_length=16)),
                ("data_origin", models.CharField(max_length=16)),
                ("published_at", models.DateTimeField(null=True)),
                ("purpose", models.CharField(max_length=32)),
                ("body", models.TextField()),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "policy_version",
            },
        ),
        migrations.AddField(
            model_name="consentgrant",
            name="policy_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.policyversion"
            ),
        ),
        migrations.CreateModel(
            name="ProfileSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(default="initial", max_length=16)),
                ("schema_version", models.CharField(max_length=32)),
                ("result", models.JSONField()),
                ("data_origin", models.CharField(max_length=16)),
                ("produced_at", models.DateTimeField()),
                (
                    "algorithm_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="core.algorithmattempt"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.child"),
                ),
            ],
            options={
                "db_table": "profile_snapshot",
            },
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.profilesnapshot"
            ),
        ),
        migrations.CreateModel(
            name="QuestionnaireVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("version", models.CharField(max_length=32)),
                ("status", models.CharField(default="draft", max_length=16)),
                ("data_origin", models.CharField(max_length=16)),
                ("published_at", models.DateTimeField(null=True)),
                ("schema_version", models.CharField(default="questionnaire-v1", max_length=32)),
                ("questions", models.JSONField()),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "questionnaire_version",
            },
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="questionnaire_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.questionnaireversion"
            ),
        ),
        migrations.CreateModel(
            name="ReportTemplateVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("version", models.CharField(max_length=32)),
                ("status", models.CharField(default="draft", max_length=16)),
                ("data_origin", models.CharField(max_length=16)),
                ("published_at", models.DateTimeField(null=True)),
                ("template", models.JSONField()),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "report_template_version",
            },
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="template_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.reporttemplateversion",
            ),
        ),
        migrations.CreateModel(
            name="ReportVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_schema_version", models.CharField(default="report-v1", max_length=32)),
                ("content", models.JSONField()),
                ("data_origin", models.CharField(max_length=16)),
                ("generated_at", models.DateTimeField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.profilesnapshot"
                    ),
                ),
                (
                    "template_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.reporttemplateversion"
                    ),
                ),
            ],
            options={
                "db_table": "report_version",
            },
        ),
        migrations.AddConstraint(
            model_name="algorithmattempt",
            constraint=models.UniqueConstraint(
                fields=("session", "attempt_no"), name="attempt_number_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="algorithmattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["prepared", "running", "unknown"])),
                fields=("session",),
                name="attempt_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="algorithmattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["prepared", "running", "succeeded", "failed", "unknown", "cancelled"],
                    )
                ),
                name="attempt_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobattempt",
            constraint=models.UniqueConstraint(
                fields=("job", "attempt_no"), name="job_attempt_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                fields=("purpose", "version"), name="policy_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("purpose",),
                name="policy_one_published",
            ),
        ),
        migrations.AddConstraint(
            model_name="policyversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("purpose__in", ["assessment_processing", "dingdong_sync"])),
                name="policy_purpose_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentgrant",
            constraint=models.UniqueConstraint(
                fields=("granted_by", "create_request_key"), name="consent_create_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="consentgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoked_at__isnull", True)),
                fields=("child", "purpose"),
                name="consent_one_active",
            ),
        ),
        migrations.AddIndex(
            model_name="profilesnapshot",
            index=models.Index(
                fields=["child", "produced_at"], name="profile_sna_child_i_c98808_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind", "initial")), name="m2_profile_initial_only"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionnaireversion",
            constraint=models.UniqueConstraint(
                fields=("code", "version"), name="questionnaire_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionnaireversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("code",),
                name="questionnaire_one_published",
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentsession",
            index=models.Index(
                fields=["child", "created_at"], name="assessment__child_i_ec533b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsession",
            constraint=models.UniqueConstraint(
                fields=("started_by", "create_request_key"), name="assessment_create_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="assessmentsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "draft",
                            "ready",
                            "processing",
                            "needs_recapture",
                            "result_unknown",
                            "completed",
                            "cancelled",
                            "expired",
                        ],
                    )
                ),
                name="assessment_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplateversion",
            constraint=models.UniqueConstraint(
                fields=("code", "version"), name="template_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="reporttemplateversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("code",),
                name="template_one_published",
            ),
        ),
        migrations.AddIndex(
            model_name="backgroundjob",
            index=models.Index(
                fields=["status", "next_attempt_at"], name="background__status_f2b3ba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="backgroundjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "pending",
                            "running",
                            "waiting",
                            "unknown",
                            "succeeded",
                            "failed",
                            "cancelled",
                        ],
                    )
                ),
                name="job_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportversion",
            constraint=models.UniqueConstraint(
                fields=("profile", "template_version"), name="report_input_unique"
            ),
        ),
    ]
