# Generated by Django 6.0.8 on 2026-09-11 06:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_backgroundjob_assessmentsession_algorithmattempt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("create_request_key", models.UUIDField()),
                ("kind", models.CharField(max_length=16)),
                ("reason_code", models.CharField(max_length=32)),
                ("status", models.CharField(default="open", max_length=16)),
                ("resolution_code", models.CharField(max_length=32, null=True)),
                ("completed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "data_request",
            },
        ),
        migrations.CreateModel(
            name="ExternalAssociation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("create_request_key", models.UUIDField()),
                ("proof_digest", models.CharField(max_length=64)),
                ("provider", models.CharField(default="dingdong", max_length=32)),
                ("external_subject_id", models.CharField(max_length=255)),
                ("subject_kind", models.CharField(default="test_child", max_length=32)),
                ("status", models.CharField(default="verified", max_length=16)),
                ("verified_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(null=True)),
                ("data_origin", models.CharField(default="synthetic", max_length=16)),
            ],
            options={
                "db_table": "external_association",
            },
        ),
        migrations.CreateModel(
            name="JobObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "job_observation",
            },
        ),
        migrations.CreateModel(
            name="ObservationBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logical_key", models.CharField(max_length=128)),
                ("source_version", models.CharField(max_length=64)),
                ("revision_no", models.PositiveIntegerField()),
                ("schema_version", models.CharField(default="test-observation-v1", max_length=32)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                ("metrics", models.JSONField()),
                ("content_digest", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "observation_batch",
            },
        ),
        migrations.CreateModel(
            name="ProfileObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "profile_observation",
            },
        ),
        migrations.CreateModel(
            name="RuleVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("version", models.CharField(max_length=32)),
                ("status", models.CharField(default="draft", max_length=16)),
                ("data_origin", models.CharField(max_length=16)),
                ("published_at", models.DateTimeField(null=True)),
                ("config", models.JSONField()),
            ],
            options={
                "db_table": "rule_version",
            },
        ),
        migrations.CreateModel(
            name="SyncCheckpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="enabled", max_length=16)),
                ("cursor", models.PositiveBigIntegerField(default=0)),
                ("last_success_at", models.DateTimeField(null=True)),
                ("next_due_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(max_length=64, null=True)),
            ],
            options={
                "db_table": "sync_checkpoint",
            },
        ),
        migrations.RemoveConstraint(
            model_name="profilesnapshot",
            name="m2_profile_initial_only",
        ),
        migrations.AddField(
            model_name="profilesnapshot",
            name="generation_key",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="profilesnapshot",
            name="window_end",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="profilesnapshot",
            name="window_start",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="backgroundjob",
            name="profile",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.profilesnapshot"
            ),
        ),
        migrations.AlterField(
            model_name="profilesnapshot",
            name="algorithm_attempt",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.algorithmattempt"
            ),
        ),
        migrations.AddField(
            model_name="datarequest",
            name="child",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.child"
            ),
        ),
        migrations.AddField(
            model_name="datarequest",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="externalassociation",
            name="child",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.child"),
        ),
        migrations.AddField(
            model_name="externalassociation",
            name="consent_grant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.consentgrant"
            ),
        ),
        migrations.AddField(
            model_name="externalassociation",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="association",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.externalassociation",
            ),
        ),
        migrations.AddField(
            model_name="jobobservation",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.backgroundjob"
            ),
        ),
        migrations.AddField(
            model_name="observationbatch",
            name="association",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.externalassociation"
            ),
        ),
        migrations.AddField(
            model_name="observationbatch",
            name="supersedes",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.observationbatch"
            ),
        ),
        migrations.AddField(
            model_name="jobobservation",
            name="observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.observationbatch"
            ),
        ),
        migrations.AddField(
            model_name="profileobservation",
            name="observation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="core.observationbatch"
            ),
        ),
        migrations.AddField(
            model_name="profileobservation",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.profilesnapshot"
            ),
        ),
        migrations.AddField(
            model_name="ruleversion",
            name="published_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="backgroundjob",
            name="rule_version",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.ruleversion"
            ),
        ),
        migrations.AddField(
            model_name="profilesnapshot",
            name="rule_version",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.ruleversion"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("algorithm_attempt__isnull", False),
                        ("kind", "initial"),
                        ("rule_version__isnull", True),
                        ("window_end__isnull", True),
                        ("window_start__isnull", True),
                    ),
                    models.Q(
                        ("algorithm_attempt__isnull", True),
                        ("kind", "stage"),
                        ("rule_version__isnull", False),
                        ("window_end__gt", models.F("window_start")),
                        ("window_start__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="profile_source_valid",
            ),
        ),
        migrations.AddField(
            model_name="synccheckpoint",
            name="association",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.externalassociation"
            ),
        ),
        migrations.AddConstraint(
            model_name="datarequest",
            constraint=models.UniqueConstraint(
                fields=("requester", "create_request_key"), name="data_request_create_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalassociation",
            constraint=models.UniqueConstraint(
                fields=("requested_by", "create_request_key"), name="association_create_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="externalassociation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "verified")),
                fields=("child", "provider"),
                name="child_one_association",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalassociation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "verified")),
                fields=("provider", "subject_kind", "external_subject_id"),
                name="subject_one_association",
            ),
        ),
        migrations.AddConstraint(
            model_name="externalassociation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("ended_at__isnull", True), ("status", "verified")),
                    models.Q(("ended_at__isnull", False), ("status", "revoked")),
                    _connector="OR",
                ),
                name="association_end_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationbatch",
            constraint=models.UniqueConstraint(
                fields=("association", "logical_key", "revision_no"),
                name="observation_revision_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationbatch",
            constraint=models.UniqueConstraint(
                fields=("association", "logical_key", "source_version"),
                name="observation_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="observationbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("window_end__gt", models.F("window_start"))),
                name="observation_window_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobobservation",
            constraint=models.UniqueConstraint(
                fields=("job", "observation"), name="job_observation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="profileobservation",
            constraint=models.UniqueConstraint(
                fields=("profile", "observation"), name="profile_observation_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ruleversion",
            constraint=models.UniqueConstraint(
                fields=("code", "version"), name="rule_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="ruleversion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("code",),
                name="rule_one_published",
            ),
        ),
    ]
