# Generated by Django 6.0.8 on 2026-09-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_datarequest_externalassociation_jobobservation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaireversion",
            name="description",
            field=models.TextField(default="仅用于测试流程，非专业量表，不作能力评价。"),
        ),
        migrations.AddField(
            model_name="questionnaireversion",
            name="purpose",
            field=models.CharField(
                choices=[("exploration", "探索偏好体验"), ("assessment", "正式测评流程（测试）")],
                default="assessment",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="questionnaireversion",
            name="title",
            field=models.CharField(default="日常情境问卷（测试）", max_length=160),
        ),
    ]
