# Generated by Django 6.0.8 on 2026-09-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_questionnaireversion_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="questionnaireversion",
            options={"verbose_name": "题库版本", "verbose_name_plural": "题库管理"},
        ),
        migrations.AlterField(
            model_name="questionnaireversion",
            name="questions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
