# Generated by Django 6.0.8 on 2026-09-16 14:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_activitycontentversion_create_request_key_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ca_account_id", models.CharField(max_length=64, unique=True)),
                ("robot_ref", models.CharField(blank=True, max_length=64, null=True)),
                ("nfc_token_hash", models.CharField(max_length=64)),
                ("status", models.CharField(default="active", max_length=16)),
                ("bind_state", models.CharField(default="unbound", max_length=16)),
                ("create_request_key", models.UUIDField()),
                ("create_payload", models.JSONField()),
                ("bound_at", models.DateTimeField()),
                ("unbound_at", models.DateTimeField(null=True)),
                (
                    "bound_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.child"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.family"
                    ),
                ),
            ],
            options={
                "verbose_name": "CA 账户",
                "verbose_name_plural": "CA 账户",
                "db_table": "ca_account",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bound_by", "create_request_key"), name="ca_account_create_unique"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("nfc_token_hash",),
                        name="ca_account_one_active_robot",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("child",),
                        name="ca_account_one_active_child",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["active", "retired"])),
                        name="ca_account_status_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("bind_state__in", ["unbound", "bound"])),
                        name="ca_account_bind_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("status", "active"), ("unbound_at__isnull", True)),
                            models.Q(("status", "retired"), ("unbound_at__isnull", False)),
                            _connector="OR",
                        ),
                        name="ca_account_end_valid",
                    ),
                ],
            },
        ),
    ]
