# Generated by Django 6.0.8 on 2026-09-17 16:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_caaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaReassessmentEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("trigger_type", models.CharField(max_length=32)),
                ("recommended_at", models.DateTimeField()),
                ("old_profile_id", models.CharField(blank=True, max_length=64, null=True)),
                ("old_persona_id", models.CharField(blank=True, max_length=64, null=True)),
                ("accepted", models.BooleanField(null=True)),
                ("responded_at", models.DateTimeField(null=True)),
                ("response_request_key", models.UUIDField(blank=True, null=True)),
                ("new_assessment_id", models.CharField(blank=True, max_length=64, null=True)),
                ("new_profile_id", models.CharField(blank=True, max_length=64, null=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("complete_request_key", models.UUIDField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("persona_switched", models.BooleanField(default=False)),
                ("pending_sync", models.BooleanField(default=False)),
                ("last_error", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "ca_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.caaccount",
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.child"),
                ),
            ],
            options={
                "verbose_name": "复测事件",
                "verbose_name_plural": "复测事件",
                "db_table": "ca_reassessment_event",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("trigger_type__in", ["low_engagement", "periodic", "manual"])
                        ),
                        name="ca_reassessment_trigger_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("accepted__isnull", True), ("responded_at__isnull", True)),
                            models.Q(("accepted__isnull", False), ("responded_at__isnull", False)),
                            _connector="OR",
                        ),
                        name="ca_reassessment_response_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", True), ("new_assessment_id__isnull", True)
                            ),
                            models.Q(
                                ("completed_at__isnull", False),
                                ("new_assessment_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="ca_reassessment_complete_valid",
                    ),
                ],
            },
        ),
    ]
