# Generated by Django 6.0.8 on 2026-09-17 19:44
#
# 复测事件的唯一性从全局 `event_id` 收窄为 `(ca_account, event_id)`（T-037）。
# 旧约束更严，所以既有数据里不可能存在「同账户同事件」的重复行，本迁移不需要
# 去重或数据回填；方向是放宽，没有行会被删或改。

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_careassessmentevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careassessmentevent",
            name="event_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="careassessmentevent",
            constraint=models.UniqueConstraint(
                fields=("ca_account", "event_id"), name="ca_reassessment_event_account_unique"
            ),
        ),
    ]
