# Generated by Django 6.0.8 on 2026-09-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_alter_careassessmentevent_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionnaireversion",
            name="purpose",
            field=models.CharField(
                choices=[("exploration", "探索偏好体验"), ("assessment", "正式测评流程")],
                default="assessment",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="questionnaireversion",
            name="title",
            field=models.CharField(default="日常情境问卷", max_length=160),
        ),
    ]
