# Generated by Django 6.0.8 on 2026-09-23 08:07

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_questionnaireversion_purpose_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DingDongPushEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=64, unique=True)),
                ("event_type", models.CharField(blank=True, default="", max_length=64)),
                ("ca_account_id", models.CharField(blank=True, default="", max_length=64)),
                ("occurred_at", models.CharField(blank=True, default="", max_length=64)),
                ("payload", models.JSONField()),
            ],
            options={
                "db_table": "dingdong_push_event",
                "indexes": [
                    models.Index(fields=["created_at"], name="dingdong_pu_created_042a89_idx")
                ],
            },
        ),
    ]
