# Generated by Django 6.0.8 on 2026-09-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_dingdongpushevent"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="smschallenge",
            name="sms_status_valid",
        ),
        migrations.AddConstraint(
            model_name="smschallenge",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["sending", "sent", "consumed", "expired", "locked", "failed"])
                ),
                name="sms_status_valid",
            ),
        ),
    ]
