# Generated by Django 6.0.8 on 2026-09-30 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_extend_sms_challenge_states"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="activitycontentversion",
            name="activity_origin",
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="exploration_result",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionnaireversion",
            name="scoring",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="questionnaireversion",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("exploration", "探索偏好体验"),
                    ("assessment", "正式测评流程"),
                    ("interest", "六岛兴趣探索"),
                    ("talent", "八维日常观察"),
                ],
                default="assessment",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="activitycontentversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_origin__in", ["synthetic", "live", "reference"])),
                name="activity_origin",
            ),
        ),
    ]
