# Generated by Django 6.0.8 on 2026-09-30 08:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_remove_activitycontentversion_activity_origin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChildCompanionPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("guide_mode", models.CharField(default="cognitive", max_length=16)),
                ("revision", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "verbose_name": "网页陪伴偏好",
                "verbose_name_plural": "网页陪伴偏好",
                "db_table": "child_companion_preference",
            },
        ),
        migrations.AddField(
            model_name="activityrecord",
            name="guide_mode",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddConstraint(
            model_name="activityrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("guide_mode__in", ["", "cognitive", "imitative", "reverse", "open"])
                ),
                name="activity_guide_mode_valid",
            ),
        ),
        migrations.AddField(
            model_name="childcompanionpreference",
            name="child",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="core.child"
            ),
        ),
        migrations.AddConstraint(
            model_name="childcompanionpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("guide_mode__in", ["cognitive", "imitative", "reverse", "open"])
                ),
                name="companion_preference_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="childcompanionpreference",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="companion_preference_revision_positive",
            ),
        ),
    ]
