# Generated by Django 6.0.8 on 2026-09-30 13:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_existing_demo(apps, schema_editor):
    apps.get_model("core", "CaAccount").objects.filter(ca_account_id="ca_dingdong").update(
        prototype_demo=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_childcompanionpreference_activityrecord_guide_mode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrototypeReportSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_account_id", models.CharField(max_length=64)),
                ("weekly_turns", models.PositiveSmallIntegerField()),
                ("source_updated_at", models.DateTimeField()),
                ("sync_source", models.CharField(max_length=8)),
                ("content_hash", models.CharField(max_length=64)),
                ("view", models.JSONField()),
            ],
            options={
                "verbose_name": "演示伙伴报告快照",
                "verbose_name_plural": "演示伙伴报告快照",
                "db_table": "prototype_report_snapshot",
            },
        ),
        migrations.AddField(
            model_name="caaccount",
            name="prototype_demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dingdongpushevent",
            name="processing_error",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="dingdongpushevent",
            name="processing_status",
            field=models.CharField(default="received", max_length=16),
        ),
        migrations.RunPython(mark_existing_demo, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="caaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("prototype_demo", True), ("status", "active")),
                fields=("prototype_demo",),
                name="ca_account_one_active_demo",
            ),
        ),
        migrations.AddConstraint(
            model_name="dingdongpushevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("processing_status__in", ["received", "processed", "ignored", "invalid"])
                ),
                name="dingdong_push_processing_valid",
            ),
        ),
        migrations.AddField(
            model_name="prototypereportsnapshot",
            name="event",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="core.dingdongpushevent"
            ),
        ),
        migrations.AddIndex(
            model_name="prototypereportsnapshot",
            index=models.Index(
                fields=["weekly_turns", "-source_updated_at"], name="prototype_r_weekly__f776b3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="prototypereportsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("weekly_turns__in", [3, 7, 14, 21])),
                name="prototype_weekly_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="prototypereportsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("sync_source__in", ["pull", "push"])),
                name="prototype_sync_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="prototypereportsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_account_id", "ca_dingdong")),
                name="prototype_fixed_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="prototypereportsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event__isnull", True), ("sync_source", "pull")),
                    models.Q(("event__isnull", False), ("sync_source", "push")),
                    _connector="OR",
                ),
                name="prototype_event_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="prototypereportsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sync_source", "pull")),
                fields=("weekly_turns", "content_hash"),
                name="prototype_pull_content_unique",
            ),
        ),
    ]
