# Generated by Django 6.0.8 on 2026-09-30 20:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_prototypereportsnapshot_caaccount_prototype_demo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExhibitionVisitor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_entered_at", models.DateTimeField(null=True)),
                ("last_entered_at", models.DateTimeField(null=True)),
                ("last_report_viewed_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("note", models.CharField(blank=True, default="", max_length=2000)),
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "exhibition_visitor",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ExhibitionVisit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_id", models.UUIDField()),
                ("event", models.CharField(max_length=16)),
                ("response", models.JSONField()),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.exhibitionvisitor"
                    ),
                ),
            ],
            options={
                "db_table": "exhibition_visit",
            },
        ),
        migrations.AddConstraint(
            model_name="exhibitionvisitor",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["pending", "contacted", "closed"])),
                name="exhibition_followup_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="exhibitionvisitor",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="exhibition_revision_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="exhibitionvisit",
            constraint=models.UniqueConstraint(
                fields=("visitor", "request_id"), name="exhibition_visit_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="exhibitionvisit",
            constraint=models.CheckConstraint(
                condition=models.Q(("event__in", ["entered", "report_viewed"])),
                name="exhibition_event_valid",
            ),
        ),
    ]
