# Generated by Django 6.0.8 on 2026-10-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_exhibition_visits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logingrant",
            name="expires_at",
            field=models.DateTimeField(null=True),
        ),
    ]
